version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123.
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=abc123.
      - MYSQL_DATABASE=social
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pabc123.", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s

  app:
    build: .
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_TABLE=social
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=abc123.
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    ports:
      - 4000:4000